-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE EQUIPE (
id INTEGER PRIMARY KEY,
nome VARCHAR(40),
abreviacao VARCHAR(10)
)

CREATE TABLE USUARIO (
nome VARCHAR(60),
cpf INTEGER PRIMARY KEY,
email VARCHAR(255),
senha VARCHAR(20)
)

CREATE TABLE JOGADOR (
id INTEGER PRIMARY KEY,
data_nascimento VARCHAR(10),
nome VARCHAR(60),
id_equipe INTEGER,
FOREIGN KEY(id_equipe) REFERENCES EQUIPE (id)
)

CREATE TABLE TIPO_OCORRÊNCIA (
id INTEGER PRIMARY KEY,
desc VARCHAR(255)
)

CREATE TABLE OCORRÊNCIA (
id INTEGER PRIMARY KEY,
id_jogador INTEGER,
id_partida INTEGER,
id_tipo_ocorrencia INTEGER,
qtd_ocorrencia INTEGER,
FOREIGN KEY(id_jogador) REFERENCES JOGADOR (id),
FOREIGN KEY(id_tipo_ocorrencia) REFERENCES TIPO_OCORRÊNCIA (id)
)

CREATE TABLE PARTIDA´ (
id INTEGER PRIMARY KEY,
desc VARCHAR(255)
)

CREATE TABLE Favorita (
cpf INTEGER,
id_jogador INTEGER,
FOREIGN KEY(cpf) REFERENCES USUARIO (cpf),
FOREIGN KEY(id_jogador) REFERENCES JOGADOR (id)
)

CREATE TABLE participa (
id_equipe INTEGER,
id_partida INTEGER,
FOREIGN KEY(id_equipe) REFERENCES EQUIPE (id),
FOREIGN KEY(id_partida) REFERENCES PARTIDA´ (id)
)

ALTER TABLE OCORRÊNCIA ADD FOREIGN KEY(id_partida) REFERENCES PARTIDA´ (id)
